version: '3.7'

services:
  php-fpm:
    container_name: php-fpm
    build:
      dockerfile: ./.docker/Dockerfile
      context: .
      args:
        USER_ID: $USER_ID
    env_file: .env
    volumes:
      - .:/var/www/html/:delegated
      - ./vendor/:/var/www/html/vendor
